version: '3.4'

services:
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      TZ: 'EST5EDT'
      NMBD: "true"
      USER: "user;1234"
      USERID: "0"
      GROUPID: "0"
      SHARE: "server;/mnt;yes;no;no;user;'none';'none'"
      WORKGROUP: "WORKGROUP"
      RECYCLE: ""
    network_mode: host
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /home/server/:/mnt:z
